spring.application.name=booking-service

server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Database (adjust credentials)
spring.datasource.url=jdbc:postgresql://localhost:5432/bookingdb
spring.datasource.username=bookinguser
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true